apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: katalogskupin-service-monitor
  labels:
    team: katalogteam
spec:
  selector:
    matchLabels:
      app: katalog-skupin
  endpoints:
  - port: server