apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: katalogskupin-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: katalog-skupin
    spec:
      containers:
      - image: tjasaj/katalog-skupin:0.02
        name: katalog-skupin
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP
